environment: development
name: ffc-sfi-map-web
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-map-web

labels:
  component: web

appInsights:
  key:

service:
  port: 80
  type: ClusterIP

containerConfigMap:
  name: ffc-sfi-map-web-config-map

containerSecret:
  name: ffc-sfi-map-web-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 600Mi
  limitCpu: 350m
  port: 3004
  googleTagManagerKey:
  osMapApiKey:

ingress:
  class: nginx
  endpoint: ffc-sfi-map-web
  server: example.com

livenessProbe:
  path: /healthz
  port: 3004
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3004
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
